FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY trustpilot_streamlit /app/trustpilot_streamlit

EXPOSE 8501

CMD ["python", "-m", "streamlit", "run", "trustpilot_streamlit/app.py", "--server.address=0.0.0.0", "--server.port=8501", "--server.headless=true"]